general {
    disable_loading_bar = true
    grace = 5
    hide_cursor = true
}

background {
    monitor =
    path = ~/Pictures/wallpaper.jpg
    blur_passes = 2
    blur_size = 6
    color = rgba(263640ff)
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 3
    outer_color = rgba(ff6f61ff)
    inner_color = rgba(4a5a6bff)
    font_color = rgba(93a1a1ff)
    fade_on_empty = true
    rounding = 8
    placeholder_text = <i>Enter Password...</i>
}

label {
    monitor =
    text = cmd[update:1000] date "+%H:%M:%S - %Y-%m-%d"
    color = rgba(93a1a1ff)
    font_size = 50
    font_family = Noto Sans
    position = 0, 100
    halign = center
    valign = center
}
