# шрифт
font_family JetBrainsMono Nerd Font
font_size 12

# мышка
mouse_hide_wait 3.0

# копипаста
copy_on_select yes

# цвета (простая тема)
foreground #cdd6f4
background #1e1e2e

# отключить звуки
enable_audio_bell no

# # быстрые табы
# map ctrl+shift+t new_tab
# map ctrl+shift+w close_tab
#
# # сплиты
# map ctrl+shift+enter new_window
# map ctrl+shift+h neighboring_window left
# map ctrl+shift+l neighboring_window right
# map ctrl+shift+j neighboring_window down
# map ctrl+shift+k neighboring_window up
